# MODEL_SVM

**Let's start by uploading the dataset already normalized and defining the X and y for our model**

In [1]:
import pandas as pd
import numpy as np

In [2]:
churn_svm = pd.read_csv('Churn_Norm.csv')

In [3]:
churn_svm.head()

CreditScore       Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0        0.538  0.324324     0.2  0.000000       0.000000        1.0   
1        0.516  0.310811     0.1  0.334031       0.000000        0.0   
2        0.304  0.324324     0.8  0.636357       0.666667        1.0   
3        0.698  0.283784     0.1  0.000000       0.333333        0.0   
4        1.000  0.337838     0.2  0.500246       0.000000        1.0   

   IsActiveMember  EstimatedSalary  Exited  Gender_Int  Geography_Germany  \
0             1.0         0.506735     1.0         1.0                0.0   
1             1.0         0.562709     0.0         1.0                0.0   
2             0.0         0.569654     1.0         1.0                0.0   
3             0.0         0.469120     0.0         1.0                0.0   
4             1.0         0.395400     0.0         1.0                0.0   

   Geography_Spain  Balance_Int  
0              0.0          0.0  
1              1.0          1.0  
2              0.0          1.0  
3              0.0          0.0  
4              1.0          1.0

In [4]:
X = churn_svm.drop(['Exited'], axis=1)
y = churn_svm.Exited

In [5]:
X

CreditScore       Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0           0.538  0.324324     0.2  0.000000       0.000000        1.0   
1           0.516  0.310811     0.1  0.334031       0.000000        0.0   
2           0.304  0.324324     0.8  0.636357       0.666667        1.0   
3           0.698  0.283784     0.1  0.000000       0.333333        0.0   
4           1.000  0.337838     0.2  0.500246       0.000000        1.0   
...           ...       ...     ...       ...            ...        ...   
9995        0.842  0.283784     0.5  0.000000       0.333333        1.0   
9996        0.332  0.229730     1.0  0.228657       0.000000        1.0   
9997        0.718  0.243243     0.7  0.000000       0.000000        0.0   
9998        0.844  0.324324     0.3  0.299226       0.333333        1.0   
9999        0.884  0.135135     0.4  0.518708       0.000000        1.0   

      IsActiveMember  EstimatedSalary  Gender_Int  Geography_Germany  \
0                1.0         0.506735         1.0                0.0   
1                1.0         0.562709         1.0                0.0   
2                0.0         0.569654         1.0                0.0   
3                0.0         0.469120         1.0                0.0   
4                1.0         0.395400         1.0                0.0   
...              ...              ...         ...                ...   
9995             0.0         0.481341         0.0                0.0   
9996             1.0         0.508490         0.0                0.0   
9997             1.0         0.210390         1.0                0.0   
9998             0.0         0.464429         0.0                1.0   
9999             0.0         0.190914         1.0                0.0   

      Geography_Spain  Balance_Int  
0                 0.0          0.0  
1                 1.0          1.0  
2                 0.0          1.0  
3                 0.0          0.0  
4                 1.0          1.0  
...               ...          ...  
9995              0.0          0.0  
9996              0.0          1.0  
9997              0.0          0.0  
9998              0.0          1.0  
9999              0.0          1.0  

[10000 rows x 12 columns]

In [6]:
y

0       1.0
1       0.0
2       1.0
3       0.0
4       0.0
       ... 
9995    0.0
9996    0.0
9997    1.0
9998    1.0
9999    0.0
Name: Exited, Length: 10000, dtype: float64

**We will try our first different models:**

**1. LINEAR**

**2. RBF**

**3. POLY**

## SMV (Linear)

In [7]:
from sklearn.svm import SVC

In [8]:
svm_linear = SVC(kernel='linear', C=10)

In [9]:
svm_linear.fit(X,y)

SVC(C=10, kernel='linear')

In [10]:
print('Linear SVC will give us:', round(svm_linear.score(X,y),3))

Linear SVC will give us: 0.796


**We split the data into train_test**

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1)

In [12]:
svm_linear.fit(X_train, y_train)

svm_linear.fit(X_test, y_test)

print('Linear SVC trained will give us:', round(svm_linear.score(X_train,y_train),3))

print('Linear SVC test will give us:', round(svm_linear.score(X_test,y_test),3))

Linear SVC trained will give us: 0.797
Linear SVC test will give us: 0.788


**Conclusions**

1. Our SVC trained will give the exact same results.
2. Our SVC test will give us better results, which is overfitting.

## SMV_RBF

In [13]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
X = StandardScaler().fit_transform(X)

In [14]:
svm_rbf = SVC(kernel='rbf', C=10)

In [15]:
svm_rbf.fit(X,y)

SVC(C=10)

In [16]:
print('RBF SVC will give us:', round(svm_rbf.score(X,y),2))

RBF SVC will give us: 0.89


In [17]:
svm_rbf.fit(X_train, y_train)

svm_rbf.fit(X_test, y_test)

print('RBF SVC trained will give us:', round(svm_rbf.score(X_train,y_train),3))

print('RBF SVC test will give us:', round(svm_rbf.score(X_test,y_test),3))

RBF SVC trained will give us: 0.828
RBF SVC test will give us: 0.882


**Conclusions**

1. Our RBF trained will give a lower accuracy but higher than the initial 80%.
2. Our RBF test will give us better results, which is overfitting.

## SMV_POLY

In [18]:
svm_poly = SVC(kernel='poly', C=10)

svm_poly.fit(X,y)

In [20]:
svm_poly.fit(X,y)

SVC(C=10, kernel='poly')

In [21]:
print('Poly SVC will give us:', round(svm_poly.score(X,y),3))

Poly SVC will give us: 0.87


In [22]:
svm_poly.fit(X_train, y_train)

svm_poly.fit(X_test, y_test)

print('Poly SVC trained will give us:', round(svm_poly.score(X_train,y_train),3))

print('Poly SVC test will give us:', round(svm_poly.score(X_test,y_test),3))

Poly SVC trained will give us: 0.834
Poly SVC test will give us: 0.894


**Conclusions**

1. Our Poly SVC trained will give a lower accuracy but higher than the initial 80%.
2. Our Poly SVC test will give us better results, which is overfitting.

**To sum up:**

The best model is RBF because it will give us an 0,89% accuracy.
Followed by Poly with an 0,87% and last Linear with an 0,79%.

## PCA

Let's see if our results improve with a PCA

In [23]:
from sklearn.decomposition import PCA

In [24]:
pca = PCA(n_components=8)

In [25]:
pc = pca.fit_transform(X, y)

In [26]:
pc.shape

(10000, 8)

In [27]:
svm_linear.fit(pc, y)
print('Linear SVC with PCA will give us:', round(svm_linear.score(pc,y),3))

Linear SVC with PCA will give us: 0.796


In [28]:
svm_rbf.fit(pc, y)
print('Linear SVC with PCA will give us:', round(svm_rbf.score(pc,y),3))

Linear SVC with PCA will give us: 0.856


In [29]:
svm_poly.fit(pc, y)
print('Linear SVC with PCA will give us:', round(svm_poly.score(pc,y),3))

Linear SVC with PCA will give us: 0.822


**With a PCA of 8 components, the results will be worse**

In [30]:
pca2 = PCA(n_components=2)

In [31]:
pc2 = pca2.fit_transform(X, y)

In [32]:
pc2.shape

(10000, 2)

In [33]:
svm_linear.fit(pc2, y)
print('Linear SVC with PCA will give us:', round(svm_linear.score(pc2,y),3))

Linear SVC with PCA will give us: 0.796


In [34]:
svm_rbf.fit(pc2, y)
print('Linear SVC with PCA will give us:', round(svm_rbf.score(pc2,y),3))

Linear SVC with PCA will give us: 0.811


In [35]:
svm_poly.fit(pc2, y)
print('Linear SVC with PCA will give us:', round(svm_poly.score(pc2,y),3))

Linear SVC with PCA will give us: 0.796


**With a PCA of 2 components, the results will be worse than with 8**

## LDA

Let's see if our results improve with a LDA

In [36]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [37]:
lda = LinearDiscriminantAnalysis(n_components=1)

lda = lda.fit(X,y)

lda.score(X,y)

0.8075

**Our results are not improving with LDA**

## Applying Under_Sampling and Over_sampling

In [40]:
from imblearn.under_sampling import NearMiss, RandomUnderSampler
from imblearn.over_sampling import SMOTE

random_sample = RandomUnderSampler(random_state = 42)

X_rus, y_rus = random_sample.fit_resample(churn_svm.drop(['Exited'], axis=1),y = churn_svm.Exited) 

print(X_rus.shape)
print(y_rus.shape)

(4074, 12)
(4074,)


In [41]:
nearmiss = NearMiss()

X_nearmiss, y_nearmiss = nearmiss.fit_resample(churn_svm.drop(['Exited'], axis=1),y = churn_svm.Exited) 


print(X_nearmiss.shape)
print(y_nearmiss.shape)

(4074, 12)
(4074,)


In [42]:
X_train_rus, X_test_rus, y_train_rus, y_test_rus = train_test_split(X_rus, y_rus, random_state=42, test_size=0.2)
X_train_nr, X_test_nr, y_train_nr, y_test_nr = train_test_split(X_nearmiss, y_nearmiss,random_state=42, test_size=0.2)

In [43]:
y_pred_rus = svm_rbf.fit(X_train_rus, y_train_rus).predict(X_test_rus)

In [44]:
y_pred_nearmiss = svm_rbf.fit(X_train_nr, y_train_nr).predict(X_test_nr)

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [46]:
print(confusion_matrix(y_test_rus,y_pred_rus))
print(classification_report(y_test_rus, y_pred_rus))
print(confusion_matrix(y_test_nr,y_pred_nearmiss))
print(classification_report(y_test_nr, y_pred_nearmiss))

[[348  95]
 [112 260]]
              precision    recall  f1-score   support

         0.0       0.76      0.79      0.77       443
         1.0       0.73      0.70      0.72       372

    accuracy                           0.75       815
   macro avg       0.74      0.74      0.74       815
weighted avg       0.75      0.75      0.75       815

[[371  72]
 [141 231]]
              precision    recall  f1-score   support

         0.0       0.72      0.84      0.78       443
         1.0       0.76      0.62      0.68       372

    accuracy                           0.74       815
   macro avg       0.74      0.73      0.73       815
weighted avg       0.74      0.74      0.73       815



In [47]:
oversample = SMOTE()
X, y = oversample.fit_resample(X, y)

In [48]:
X_train_ov, X_test_ov, y_train_ov, y_test_ov = train_test_split(X, y, random_state=42, test_size=0.2)

In [49]:
y_pred_ov = svm_rbf.fit(X_train_ov, y_train_ov).predict(X_test_ov)

In [51]:
print(confusion_matrix(y_test_ov,y_pred_ov))
print(classification_report(y_test_ov, y_pred_ov))

[[1329  304]
 [ 212 1341]]
              precision    recall  f1-score   support

         0.0       0.86      0.81      0.84      1633
         1.0       0.82      0.86      0.84      1553

    accuracy                           0.84      3186
   macro avg       0.84      0.84      0.84      3186
weighted avg       0.84      0.84      0.84      3186



**Our model does not improve**

## Conclusion

**Our model selected would be RBF as it is**